"""
Prompt templates for the AI Code Generator agents.

Each prompt is carefully crafted to guide the LLM toward generating
structured, coherent project plans and code implementations.
"""


def planner_prompt(user_prompt: str) -> str:
    """
    Prompt for the Planner Agent.
    
    Guides the LLM to convert a user's natural language request into
    a structured engineering project plan with all necessary files.
    
    Args:
        user_prompt: The user's description of what to build
        
    Returns:
        Complete prompt for the Planner Agent
    """
    PLANNER_PROMPT = f"""You are the PLANNER agent. Your task is to convert a user's request into a comprehensive engineering project plan.

User Request:
{user_prompt}

Output a detailed project plan that includes:
1. Project name (descriptive, CamelCase)
2. One-line description of the application
3. Technology stack (languages, frameworks, libraries)
4. List of key features to implement
5. Complete file structure with purposes for each file

Ensure your plan is realistic, well-organized, and complete enough for an architect to break down into implementation tasks.
"""
    return PLANNER_PROMPT


def architect_prompt(plan) -> str:
    """
    Prompt for the Architect Agent.
    
    Guides the LLM to break down a project plan into explicit,
    orderable implementation tasks with dependencies.
    
    Args:
        plan: The Plan object generated by the Planner
        
    Returns:
        Complete prompt for the Architect Agent
    """
    ARCHITECT_PROMPT = f"""You are the ARCHITECT agent. Your task is to break down a project plan into explicit implementation tasks.

Project Plan:
Name: {plan.name}
Description: {plan.description}
Tech Stack: {plan.techstack}
Features: {', '.join(plan.features)}

Files to Create:
{chr(10).join([f'- {f.path}: {f.purpose}' for f in plan.files])}

Your Job:
1. For each FILE in the plan, create one or more IMPLEMENTATION TASKS
2. Order tasks by dependencies (dependencies first)
3. Each task must be SELF-CONTAINED but carry FORWARD context

For each implementation task, specify:
- Exact filepath to create/modify
- Specific what to implement (function names, class names, logic)
- Variable names and data structures
- How this task depends on previous tasks
- Expected function signatures and return types
- Integration details with other modules

Ensure tasks are clear enough for a coder agent to implement them without ambiguity.
"""
    return ARCHITECT_PROMPT


def coder_system_prompt() -> str:
    """
    System prompt for the Coder Agent (ReAct pattern).
    
    Sets up the coder agent's behavior and tool usage patterns.
    
    Returns:
        System prompt for the Coder Agent
    """
    CODER_SYSTEM_PROMPT = """You are the CODER agent. Your task is to implement specific engineering tasks to build an application.

You have access to tools:
- read_file(path): Read existing file content for context
- write_file(path, content): Write/create files
- list_files(directory): Explore the project structure
- get_current_directory(): Know your working directory

Your Implementation Strategy:
1. FIRST: Read any existing files for context and imports
2. REVIEW: Check other files to understand the overall structure
3. IMPLEMENT: Write complete, production-ready code
4. INTEGRATE: Ensure imports and function signatures match

Critical Rules:
- Implement the FULL file content, not just snippets
- Maintain consistent naming across all files (variables, functions, imports)
- When importing from other files, ensure those files and functions exist
- Include proper error handling
- Add docstrings to all functions and classes
- Follow the specified technology stack and architecture
- Maintain backward compatibility with existing code

Always use the write_file tool to save your work. Don't just describe what you would write.
"""
    return CODER_SYSTEM_PROMPT
