"""
Pydantic models for the AI Code Generator state management.

Defines the data structures that flow through the agent pipeline,
ensuring type safety and validation of all agent outputs.
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional


# ==================== FILE STRUCTURE ====================

class File(BaseModel):
    """
    Represents a file to be created or modified.
    
    Attributes:
        path: The file path relative to project root
        purpose: Description of the file's purpose in the project
    """
    path: str = Field(description="The path to the file to be created or modified")
    purpose: str = Field(
        description="The purpose of the file, e.g. 'main application logic', 'data processing module', etc."
    )


# ==================== PROJECT PLAN ====================

class Plan(BaseModel):
    """
    Represents a complete project plan generated by the Planner Agent.
    
    Contains all information needed for the Architect to create implementation tasks.
    
    Attributes:
        name: Project name
        description: One-line project description
        techstack: Technologies and frameworks to use
        features: List of features to implement
        files: List of files to create with their purposes
    """
    name: str = Field(
        description="The name of the application to be built"
    )
    description: str = Field(
        description="A one-line description of the app to be built, e.g. 'A web application for managing personal finances'"
    )
    techstack: str = Field(
        description="The tech stack to be used for the app, e.g. 'python', 'javascript', 'react', 'flask', etc."
    )
    features: list[str] = Field(
        description="A list of features that the app should have, e.g. 'user authentication', 'data visualization', etc."
    )
    files: list[File] = Field(
        description="A list of files to be created, each with a 'path' and 'purpose'"
    )


# ==================== IMPLEMENTATION TASKS ====================

class ImplementationTask(BaseModel):
    """
    Represents a single implementation task for the Coder Agent.
    
    Each task should be specific, self-contained, but carry forward context
    from previous tasks.
    
    Attributes:
        filepath: Path to the file being modified or created
        task_description: Detailed description of what to implement
    """
    filepath: str = Field(
        description="The path to the file to be modified or created"
    )
    task_description: str = Field(
        description="A detailed description of the task to be performed on the file, including specific function/class names, variable names, and integration details"
    )


# ==================== TASK PLAN ====================

class TaskPlan(BaseModel):
    """
    Represents the complete implementation plan generated by the Architect Agent.
    
    Contains all implementation tasks ordered by dependencies.
    
    Attributes:
        implementation_steps: List of implementation tasks in dependency order
    """
    implementation_steps: list[ImplementationTask] = Field(
        description="A list of implementation steps to be taken, ordered by dependencies"
    )
    model_config = ConfigDict(extra="allow")


# ==================== CODER STATE ====================

class CoderState(BaseModel):
    """
    Maintains state for the Coder Agent across multiple invocations.
    
    Tracks progress through the implementation tasks.
    
    Attributes:
        task_plan: The complete task plan to execute
        current_step_idx: Index of the current step being implemented (0-based)
        current_file_content: Optional content of the file currently being edited
    """
    task_plan: TaskPlan = Field(
        description="The plan for tasks to be implemented"
    )
    current_step_idx: int = Field(
        default=0,
        description="The index of the current step in the implementation steps (0-based)"
    )
    current_file_content: Optional[str] = Field(
        default=None,
        description="The content of the file currently being edited or created (optional)"
    )
